// 广告学习中心 · 视频数据
// 视频托管在 Google Drive，嵌入地址格式：https://drive.google.com/file/d/<id>/preview
// 追加视频：在下方数组加一行即可，platform 取 google / meta / assets
const VIDEOS = [
  { n: "01", platform: "google", group: "入门必看", id: "1EkMCVoQhS00fe98baRk_6FaNfJk_kF_w", title: "Google广告投放前必做事项（为什么必投 Google 广告）" },
  { n: "02", platform: "meta", group: "入门必看", id: "1NixmkImChLi4gxDx0cIE1q22S8lW-cGc", title: "Meta广告投放前必做事项（为什么必投 Meta 广告）" },
  { n: "03", platform: "google", group: "入门必看", id: "12dw0zLe-gIRHNRRaGl-RrzYFXgdphceT", title: "[仅新手看] Google广告后台常用功能介绍" },
  { n: "04", platform: "meta", group: "入门必看", id: "1t-Mv7qttQyPo0sQ_Ny44uSn7jyLRzllo", title: "[仅新手看] Meta广告后台常用功能介绍" },
  { n: "05", platform: "meta", group: "广告结构", id: "15tC3aVnCQnD48ZiqHXt3muzHb2rsb0vE", title: "效果递进式爆款素材驱动Meta Ads广告结构" },
  { n: "06", platform: "meta", group: "广告结构", id: "1tWttY8tQEPukebIGjJB6QenQPZXuzOzV", title: "测试组广告系列结构和创建演示" },
  { n: "07", platform: "meta", group: "素材策略", id: "1hsJJlYXhrs90dV1Iv5NMeDpNhyiMzIVm", title: "爆款图片素材测试策略" },
  { n: "08", platform: "meta", group: "AI 提效", id: "10IMZQ8gBr--0iudeA5zS5FTmBPvfdrdI", title: "AI赋能 - 爆款图片数据分析和创意发散提示词" },
  { n: "09", platform: "meta", group: "AI 提效", id: "1GAKT3qQ2c7BUYKQ7sTwIexW8u3yh4vop", title: "AI赋能 - 爆款图片素材批量生成提示词" },
  { n: "10", platform: "meta", group: "素材策略", id: "11sAZx-2_Bk4Me-Z2ignNY9z2DOhObnvL", title: "爆款短视频素材测试策略脑图" },
  { n: "11", platform: "meta", group: "AI 提效", id: "1ZAuFB7R3H1IHk00pKRnqWVnRkkPtQDHC", title: "AI赋能 - 爆款短视频数据分析和创意发散提示词" },
  { n: "12", platform: "meta", group: "AI 提效", id: "1omk7D6WIo5EZar5DGeTGCQRNPIgy-_c4", title: "AI赋能 - 爆款视频脚本创意批量生成提示词" },
  { n: "13", platform: "meta", group: "广告结构", id: "1z7J6_6O3dUCvR0jxsB8wM50EdRQ6cp1z", title: "扩量组泛投组广告系列" },
  { n: "14", platform: "meta", group: "广告结构", id: "1YF0L_JfYfYZzDRUGOxfa3PRHWKsosleR", title: "扩量组兴趣组广告系列" },
  { n: "15", platform: "meta", group: "广告结构", id: "18VFYcvxj56zXUBn2-afJGKqYohYS3g5G", title: "扩量组类似组广告系列" },
  { n: "16", platform: "meta", group: "广告结构", id: "1CzItHEiUrxW-nfrPODBLGl4yQ-feFMHt", title: "特殊组再营销组广告系列" },
  { n: "17", platform: "meta", group: "广告结构", id: "18Hr46ZNzZImPJ_pFaUpNFiXhzKiG4KKA", title: "特殊组促销活动组广告系列" },
  { n: "18", platform: "meta", group: "广告结构", id: "11fS_UVHNAJbyFIyC8VZ3grBxBV7cgVf9", title: "特殊组进阶赋能型目录广告" },
  { n: "19", platform: "meta", group: "广告结构", id: "1q71_2rbufoHRQUO4vC-EkKofQdiCUycf", title: "复购组广告系列" },
  { n: "20", platform: "meta", group: "投放技巧", id: "1tpzzRBtMbOu9cJPdJtiqHNQPijnug3Y3", title: "引用帖子ID投放Meta广告的方法" },
  { n: "21", platform: "meta", group: "投放技巧", id: "1-J2RYry92ZvkVQwsRKs_3MpJi_5cwo_9", title: "Meta Ads数据列设置" },
  { n: "22", platform: "meta", group: "投放技巧", id: "169SCzK857N5n5HaRLKu7Q9km6F8dkHjp", title: "Meta广告每日简单优化地图" },
  { n: "23", platform: "meta", group: "投放技巧", id: "1uL8tB19AZI3a5jzijMKsJfA2MO1xKp1K", title: "使用Canva去除图片上的水印" },
  { n: "24", platform: "google", group: "广告结构", id: "1VfpUVHBk8SAN6z5BxVDk676nmlRqOkku", title: "全漏斗收割式的 Google Ads 高转化结构" },
  { n: "25", platform: "google", group: "PMAX 系列", id: "1F8d3-xxdY6aFah4vVTpA8zHO122Vxo6F", title: "基础必建：PMAX 1 的创建方法和细节" },
  { n: "26", platform: "google", group: "PMAX 系列", id: "1Ccx8wrHy6f6DZq_aAah7UjOaTAzO_71r", title: "初步扩量：PMAX 2 的创建方法和细节" },
  { n: "27", platform: "google", group: "PMAX 系列", id: "10X3QsZqDa1yv_DDQ3DiZSbgIc7p4d7Lr", title: "关键扩量：PMAX 3-n 的创建方法和细节" },
  { n: "28", platform: "google", group: "PMAX 系列", id: "1hQQMLWJ0thOPwVQtjCOJpzXhyBFVKCJm", title: "高潜力的 PMAX 的创建方法和细节" },
  { n: "29", platform: "google", group: "PMAX 系列", id: "1YenChfjLfx5Eepbc_zee7dOMCV-L9REZ", title: "B2C 必建：购物流量 PMAX 的创建方法和细节" },
  { n: "30", platform: "google", group: "搜索广告系列", id: "1SL0fL-5tpx3CMrH9KhypcO8fmuCs_Kud", title: "基础必建：搜索广告系列1 的创建方法和细节" },
  { n: "31", platform: "google", group: "搜索广告系列", id: "19hFGYXJRw1HBdAVadmPrQoEZi_84xIzN", title: "初步扩量：搜索广告系列2 的创建方法和细节" },
  { n: "32", platform: "google", group: "搜索广告系列", id: "1cWAatFEt1Xuvi5pdzp3BUkZxC1c9cZ58", title: "打开上层漏斗：搜索广告系列3 的创建方法和细节" },
  { n: "33", platform: "google", group: "其他流量", id: "14TKewCUKdW4jqIqKPbw1rNLfZKEbmVuH", title: "打开上层漏斗：Demand-gen 的多种玩法和创建过程" },
  { n: "34", platform: "google", group: "其他流量", id: "1UBeMQ_Al-1p6tbeJnYS6RBppRx5au_mW", title: "购物流量扩量 - Feed的优化" },
  { n: "35", platform: "google", group: "B2B 专题", id: "1UWzsbOmyFJprcfU7JIlzjxf1vdvaQXkX", title: "在 Google 上找到你行业的B2B潜在客户" },
  { n: "36", platform: "google", group: "B2B 专题", id: "1alkoYhZToTX0eZnIvv3jO5Mv0X3TsSye", title: "做出你行业的Google Ads B2B五大关键字分类表 (Codex 智能体一键做表)" },
  { n: "37", platform: "google", group: "B2B 专题", id: "12xRoaYAknxIIaq_sLPMcqkXCxueEBWJb", title: "B2B Google广告系列结构" },
  { n: "38", platform: "google", group: "B2B 专题", id: "1xjJXcCzX7zFbZKFu0datyqVtyzmMiz70", title: "B2B 品牌词搜索广告系列创建演示和设置细节" },
  { n: "39", platform: "google", group: "B2B 专题", id: "1M4vkQwnFIFyNqA2YXhmAGPuhw55jr4Wj", title: "B2B 精准流量搜索广告系列创建演示和搜索广告优化思路" },
  { n: "40", platform: "google", group: "B2B 专题", id: "1eBrU1MpegQDiO8yKJ4iYmdpXz2e_ojPO", title: "B2B PMAX 广告系列的创建演示和设置细节" },
  { n: "41", platform: "assets", group: "素材提示词课程", id: "14nRmre2pua5_Z6WNJMJFQILIopBVTsro", title: "素材提示词课程介绍" },
  { n: "42", platform: "assets", group: "素材提示词课程", id: "1skFjDHFaHUZB2WhfTNg8H6MgPK0k7PgN", title: "爆款图片数据分析和创意发散提示词" },
  { n: "43", platform: "assets", group: "素材提示词课程", id: "1YForhksIkzCqCnFfOT1NrnpCKahAK5ID", title: "爆款图片素材批量生成提示词" },
  { n: "44", platform: "assets", group: "素材提示词课程", id: "1MU0x3Ewar3cdQ0UbOg2rBjsgQfKwWBuL", title: "爆款短视频数据分析和创意发散提示词" },
  { n: "45", platform: "assets", group: "素材提示词课程", id: "1Bb2I1F8jwi-suY9-zZXzO8ui7ORBEJsK", title: "爆款视频脚本创意批量生成提示词" },
];
